# Generated by Django 5.0.7 on 2024-11-03 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
        ('jobalignment', '0002_jobvacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvpdf', models.FileField(upload_to='pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='Accounting.user')),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacancys', to='Accounting.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
