# Generated by Django 5.0.7 on 2024-11-03 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
        ('jobalignment', '0003_remove_workexperience_user_cv_delete_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancys', to='Accounting.user'),
        ),
    ]
