# Generated by Django 5.0.7 on 2024-11-03 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobalignment', '0004_alter_cv_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancys', to='jobalignment.jobvacancy'),
        ),
    ]
