# Generated by Django 5.0.7 on 2024-11-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobalignment', '0005_alter_cv_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cvpdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
