# Generated by Django 5.0.7 on 2024-11-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobalignment', '0006_alter_cv_cvpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.TextField()),
                ('probability', models.IntegerField()),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobalignment.cv')),
            ],
        ),
    ]
